FROM node:8
RUN apt-get update && apt-get -y upgrade

# Set environment variables
ENV appDir /app

# Set the work directory
RUN mkdir -p /app
WORKDIR ${appDir}

# Install dev dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y mysql-client vim

#Expose the port
EXPOSE 3000
EXPOSE 9229

ENTRYPOINT sleep infinity